url: https://chapliza.github.io
baseurl: /me/

# Site settings
title: Meet Liza
email: chapliza@icloud.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:

- name: Elizaveta Chaplygina
  pic: 2
  position: Data Analyst
  social:
    - title: twitter
      url: https://twitter.com/chapliza
    - title: facebook
      url: https://www.facebook.com/chapliza
    - title: linkedin
      url: https://www.linkedin.com/in/chapliza/
    - title: github
      url: https://github.com/chapliza
    - title: email
      url: chapliza@icloud.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/chapliza
  - title: facebook
    url: https://www.facebook.com/chapliza
  - title: github
    url: https://github.com/chapliza

# Postal address (add as many lines as necessary)
address:
  - line: 388 Beale
  - line: San Francisco, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
